/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RestaurantManager;
import java.awt.Component;
import java.awt.TextField;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author alexa
 */
public class RestaurantManager extends javax.swing.JFrame {

    /**
     * Creates new form RestaurantManager
     */
    public RestaurantManager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jbtReset = new javax.swing.JButton();
        jbtReceipt = new javax.swing.JButton();
        jbtTotal = new javax.swing.JButton();
        jbtExit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jlbTax = new javax.swing.JLabel();
        jlbSubtotal = new javax.swing.JLabel();
        jblTotal = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTextPizza = new javax.swing.JTextField();
        jTextPotatoes = new javax.swing.JTextField();
        jTextBurrito = new javax.swing.JTextField();
        jTextKidsMeal = new javax.swing.JTextField();
        jTextBurger = new javax.swing.JTextField();
        jTextSalad = new javax.swing.JTextField();
        jblTotal4 = new javax.swing.JLabel();
        jlbSubtotal4 = new javax.swing.JLabel();
        jlbTax4 = new javax.swing.JLabel();
        jblTotal5 = new javax.swing.JLabel();
        jlbSubtotal5 = new javax.swing.JLabel();
        jlbTax5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jlbTax2 = new javax.swing.JLabel();
        jlbSubtotal2 = new javax.swing.JLabel();
        jblTotal2 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jTextWater = new javax.swing.JTextField();
        jTextSprinkleWater = new javax.swing.JTextField();
        jTextTea = new javax.swing.JTextField();
        jblTotal1 = new javax.swing.JLabel();
        jlbSubtotal1 = new javax.swing.JLabel();
        jlbTax1 = new javax.swing.JLabel();
        jlbTax3 = new javax.swing.JLabel();
        jlbSubtotal3 = new javax.swing.JLabel();
        jblTotal3 = new javax.swing.JLabel();
        jTextCappuccino = new javax.swing.JTextField();
        jTextLipton = new javax.swing.JTextField();
        jTextCola = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 12));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Restaurant Manager");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 8));

        jLabel2.setIcon(new javax.swing.ImageIcon("F:\\Java Desktop applications\\Restaurant Assets\\pizza.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(320, 320, 320)
                .addComponent(jLabel1)
                .addContainerGap(402, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 11));

        jbtReset.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jbtReset.setText("Reset");
        jbtReset.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtResetActionPerformed(evt);
            }
        });

        jbtReceipt.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jbtReceipt.setText("Receipt");
        jbtReceipt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtReceiptActionPerformed(evt);
            }
        });

        jbtTotal.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jbtTotal.setText("Total");
        jbtTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtTotalActionPerformed(evt);
            }
        });

        jbtExit.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jbtExit.setText("Exit");
        jbtExit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jbtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214)
                .addComponent(jbtReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 288, Short.MAX_VALUE)
                .addComponent(jbtReset, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addGap(235, 235, 235)
                .addComponent(jbtExit, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jbtReceipt, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jbtReset, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jbtExit, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, 1390, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 11));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 180, 250, 510));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 11));

        jTextField1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jlbTax.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jlbTax.setText("Tax");

        jlbSubtotal.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jlbSubtotal.setText("Subtotal");

        jblTotal.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jblTotal.setText("Total");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbTax, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 267, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbTax))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbSubtotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblTotal))
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 540, 550, 150));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 11));

        jTextPizza.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jTextPizza.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextPizza.setText(" 7");
        jTextPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPizzaActionPerformed(evt);
            }
        });

        jTextPotatoes.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jTextPotatoes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextPotatoes.setText("7");
        jTextPotatoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPotatoesActionPerformed(evt);
            }
        });

        jTextBurrito.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jTextBurrito.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextBurrito.setText("8");

        jTextKidsMeal.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jTextKidsMeal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextKidsMeal.setText("5");

        jTextBurger.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jTextBurger.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextBurger.setText("7");

        jTextSalad.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jTextSalad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextSalad.setText("3");

        jblTotal4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jblTotal4.setText("Caesar Salad");

        jlbSubtotal4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jlbSubtotal4.setText("Cheese Burger");

        jlbTax4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jlbTax4.setText("Kids Meal");

        jblTotal5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jblTotal5.setText("Chicken Burrito");

        jlbSubtotal5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jlbSubtotal5.setText("Mashed Potatoes");

        jlbTax5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jlbTax5.setText("Pizza Quattro Formaggi");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel4.setText("Meals");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlbSubtotal4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbTax4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jblTotal4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(118, 118, 118)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextBurger, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextSalad, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextKidsMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlbTax5, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                            .addComponent(jlbSubtotal5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jblTotal5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(118, 118, 118)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextPotatoes, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextBurrito, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextPizza, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(48, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(224, 224, 224))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTax5)
                    .addComponent(jTextPizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPotatoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbSubtotal5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextBurrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblTotal5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbTax4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextKidsMeal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbSubtotal4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextSalad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblTotal4))
                .addContainerGap())
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 550, 340));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 11));

        jlbTax2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jlbTax2.setText("Meals Cost");

        jlbSubtotal2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jlbSubtotal2.setText("Drinks Cost");

        jblTotal2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jblTotal2.setText("Total Cost");

        jTextField7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField8.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField9.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlbTax2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbSubtotal2, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(jblTotal2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbTax2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbSubtotal2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblTotal2))
                .addContainerGap())
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 550, 150));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 11));

        jTextWater.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jTextWater.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextWater.setText("0");

        jTextSprinkleWater.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jTextSprinkleWater.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextSprinkleWater.setText("0");

        jTextTea.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jTextTea.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextTea.setText("0");

        jblTotal1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jblTotal1.setText("Mint Tea");

        jlbSubtotal1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jlbSubtotal1.setText("Sprinkle Water");

        jlbTax1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jlbTax1.setText("Water");

        jlbTax3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jlbTax3.setText("Coca-Cola");

        jlbSubtotal3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jlbSubtotal3.setText("Lipton Ice");

        jblTotal3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jblTotal3.setText("Cappuccino");

        jTextCappuccino.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jTextCappuccino.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextCappuccino.setText("9");

        jTextLipton.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jTextLipton.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextLipton.setText("1");
        jTextLipton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLiptonActionPerformed(evt);
            }
        });

        jTextCola.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jTextCola.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextCola.setText("2");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel3.setText("Drinks");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlbSubtotal1, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                            .addComponent(jlbTax1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jblTotal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(118, 118, 118)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextSprinkleWater, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextTea, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextWater, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlbTax3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbSubtotal3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jblTotal3, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                        .addGap(118, 118, 118)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextLipton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextCappuccino, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextCola, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTax3)
                    .addComponent(jTextCola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextLipton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbSubtotal3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCappuccino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblTotal3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbTax1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextWater, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextSprinkleWater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbSubtotal1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblTotal1))
                .addContainerGap())
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 550, 340));

        jButton4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jButton4.setText("jButton1");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtTotalActionPerformed
        SubClass ItemCost = new SubClass();
        double iTax, iSubTotal, iTotal;
                
        //Meals
        ItemCost.CaesarSalad = ItemCost.CaesarSaladPrice * Double.parseDouble(jTextSalad.getText());
        ItemCost.CheeseBurger = ItemCost.CheeseBurgerPrice * Double.parseDouble(jTextBurger.getText());
        ItemCost.ChickenBurrito = ItemCost.ChickenBurritoPrice * Double.parseDouble(jTextBurrito.getText());
        ItemCost.KidsMenu = ItemCost.KidsMenuPrice * Double.parseDouble(jTextKidsMeal.getText());
        ItemCost.MashedPotatoes = ItemCost.MashedPotatoesPrice * Double.parseDouble(jTextPotatoes.getText());
        ItemCost.QuattroFormaggiPizza = ItemCost.QuattroFormaggiPizzaPrice * Double.parseDouble(jTextPizza.getText());
        
        //Drinks
        ItemCost.Cola = ItemCost.ColaPrice * Double.parseDouble(jTextCola.getText());
        ItemCost.LiptonIce = ItemCost.LiptonIcePrice * Double.parseDouble(jTextLipton.getText());
        ItemCost.Cappuccino = ItemCost.CappuccinoPrice * Double.parseDouble(jTextCappuccino.getText());
        ItemCost.Water = ItemCost.WaterPrice * Double.parseDouble(jTextWater.getText());
        ItemCost.SprinkleWater = ItemCost.SprinkleWaterPrice * Double.parseDouble(jTextSprinkleWater.getText());
        ItemCost.MintTea = ItemCost.MintTeaPrice * Double.parseDouble(jTextTea.getText());
        
        iSubTotal = ItemCost.GetAmount();
        iTax = ItemCost.ComputeTax(iSubTotal);
        iTotal = iSubTotal + iTax;
        
        String SubTotal = String.format("$%.2f", iSubTotal);
        jTextField3.setText(SubTotal); // Set the SubTotal Text Field to the computed SubTotal
        
        String Tax = String.format("$%.2f", iTax);
        jTextField1.setText(Tax); // Set the Tax Text Field to the computed Tax
        
        String Total = String.format("$%.2f", iTotal);
        jTextField2.setText(Total); // Set the Total Text Field to the computed Total
        
        String TotalCostOfMealsAndDrinks = String.format("$%.2f", ItemCost.GetAmount());
        jTextField7.setText(TotalCostOfMealsAndDrinks); // Set the TotalCost Text Field to the computed Total of both Meals and Drinks
        
        String Meals = String.format("$%.2f", ItemCost.Meals);
        jTextField9.setText(Meals); // Set the Meals  Text Field to the computed Total Meals
        
        String Drinks = String.format("$%.2f", ItemCost.Drinks);
        jTextField8.setText(Drinks); // Set the Drinks  Text Field to the computed Total of Drinks
        
        
    }//GEN-LAST:event_jbtTotalActionPerformed

    private void jTextLiptonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLiptonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLiptonActionPerformed

    private void jTextPotatoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPotatoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPotatoesActionPerformed

    private void jbtExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExitActionPerformed
        SubClass iExit = new SubClass();
        iExit.iExitSystem();
    }//GEN-LAST:event_jbtExitActionPerformed

    private void jbtResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtResetActionPerformed
        JTextField cleartext = null;
        // Reset Panel4 (Total)
        for (Component c:jPanel4.getComponents()){
            if (c.getClass().toString().contains("javax.swing.JTextField")){
                cleartext = (JTextField)c;
                cleartext.setText("0");
            }
        }
        // Reset Panel 5 (Meals)
        for (Component c:jPanel5.getComponents()){
            if (c.getClass().toString().contains("javax.swing.JTextField")){
                cleartext = (JTextField)c;
                cleartext.setText("0");
            }
        }
        //Reset Panel 6 (Cost)
        for (Component c:jPanel6.getComponents()){
            if (c.getClass().toString().contains("javax.swing.JTextField")){
                cleartext = (JTextField)c;
                cleartext.setText("0");
            }
        }
        //Reset Panel 7 (Drinks)
                for (Component c:jPanel7.getComponents()){
            if (c.getClass().toString().contains("javax.swing.JTextField")){
                cleartext = (JTextField)c;
                cleartext.setText("0");
            }
        }
                
        //Reset the Receipt Panel's text to null
        jTextArea1.setText(null);
    }//GEN-LAST:event_jbtResetActionPerformed

    private void jTextPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPizzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPizzaActionPerformed

    private void jbtReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtReceiptActionPerformed
        int refs = 1325 + (int) (Math.random() * 4238);

Calendar timer = Calendar.getInstance();
timer.getTime();
SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
tTime.format(timer.getTime());
SimpleDateFormat tDate = new SimpleDateFormat("dd-MM-yyyy");
tDate.format(timer.getTime());

jTextArea1.append(
    "\tRestaurant Management Systems:\n\n" +
    "Reference:\t\t\t" + refs + "\n" +
    "=====================================\n" +
    "Meals:\t\t" + jTextField9.getText() + "\n\n" +
    "Drinks:\t\t" + jTextField8.getText() + "\n\n" +
    "Cost of Items:\t" + jTextField7.getText() + "\n\n" +
    "=====================================\n" +
    "Tax:\t\t" + jTextField1.getText() + "\n\n" +
    "Subtotal:\t" + jTextField3.getText() + "\n\n" +
    "Total:\t\t" + jTextField2.getText() + "\n" +
    
    "=====================================\n" +
    "\nDate: " + tDate.format(timer.getTime()) +
    "\nTimer: " + tTime.format(timer.getTime()) +
    "\n\n\nThank you and we expect you again soon!");
        
    }//GEN-LAST:event_jbtReceiptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestaurantManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestaurantManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestaurantManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestaurantManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestaurantManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextBurger;
    private javax.swing.JTextField jTextBurrito;
    private javax.swing.JTextField jTextCappuccino;
    private javax.swing.JTextField jTextCola;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextKidsMeal;
    private javax.swing.JTextField jTextLipton;
    private javax.swing.JTextField jTextPizza;
    private javax.swing.JTextField jTextPotatoes;
    private javax.swing.JTextField jTextSalad;
    private javax.swing.JTextField jTextSprinkleWater;
    private javax.swing.JTextField jTextTea;
    private javax.swing.JTextField jTextWater;
    private javax.swing.JLabel jblTotal;
    private javax.swing.JLabel jblTotal1;
    private javax.swing.JLabel jblTotal2;
    private javax.swing.JLabel jblTotal3;
    private javax.swing.JLabel jblTotal4;
    private javax.swing.JLabel jblTotal5;
    private javax.swing.JButton jbtExit;
    private javax.swing.JButton jbtReceipt;
    private javax.swing.JButton jbtReset;
    private javax.swing.JButton jbtTotal;
    private javax.swing.JLabel jlbSubtotal;
    private javax.swing.JLabel jlbSubtotal1;
    private javax.swing.JLabel jlbSubtotal2;
    private javax.swing.JLabel jlbSubtotal3;
    private javax.swing.JLabel jlbSubtotal4;
    private javax.swing.JLabel jlbSubtotal5;
    private javax.swing.JLabel jlbTax;
    private javax.swing.JLabel jlbTax1;
    private javax.swing.JLabel jlbTax2;
    private javax.swing.JLabel jlbTax3;
    private javax.swing.JLabel jlbTax4;
    private javax.swing.JLabel jlbTax5;
    // End of variables declaration//GEN-END:variables
}
